FROM gradle:9.5.1-jdk21@sha256:4a011ed0edfe2feb7dace27d1fedf22caf217918b59932a95605cb7beec142c4 AS backend-builder
WORKDIR /app
COPY . /app
RUN ./gradlew build -x integrationTest -x test -x spotlessCheck


FROM cgr.dev/chainguard/jre@sha256:057a64e352cbd1dd81d10584ce0bb09faf384bc6bd34425a4a6d82e4092294ed
ARG SENTRY_RELEASE
COPY --from=backend-builder /app/build/libs/ris-search-*.jar /app/app.jar
EXPOSE 8090
ENV SENTRY_RELEASE=${SENTRY_RELEASE}
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
